### ISSUE TITLE
Frontend refactor checklist

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#304]
A running list of post-rails refactoring tasks to be added to and checked off over the next sprint.

*Styles // SCSS*
- [x] color vars
- [x] media queries vars
- [x] type vars
- [x] tighter modules
- [x] class naming convention cleanup

*Markup // Templating*
- [ ] Layout for form pages
- [ ] Layout for non-form pages
- [ ] Layout for upload pages
- [ ] submit button partial
- [ ] page header partial

**Comment by alanjosephwilliams** [comment]
Closing this since we ended up refactoring substantially in #340. I'll open a new issue for breaking our markup into more tailored layouts and partials.
