### ISSUE TITLE
v2 design review

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#40]
#### Description

Conduct a design review of the v1 demo. In particular, evaluate form design and offer suggestions for v2 and v3.
#### To-do
- [x] Deploy calffresh-and-so-clean
- [ ] Design review itself, with screenshots and notes
- [ ] Draft 1 pager of recommendations for v2 and v3
