### ISSUE TITLE
Initial release: document uploader

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#504]
This is a checklist issue encompassing the things we want to do prior to release (we will have cleanup after, but we should ship ASAP):

### Stretch goal = release by EOW!

- Squash bugs
  - [x] Clicking next mid-upload = doesn't upload ( #494 )
  - [x] Uploads get stuck ( #495 )
  - [x] Friendly error messages ( #497 )
  - [x] Style progress bar on mobile ( #498 )
  - [x] Fix email so that it renders HTML (or remove the HTML part since it renders as a URL in Gmail)
  - [x] Show different error for bad filetype vs. general error (which we'll say to retry on)
  - [x] QA pass
  - [x] Change final page (new page/route) to have text that reflects that the user has already uploaded documents
- [x] Test with Food Bank peeps
- [x] Mini training/FYI with RM staff (confirm link works)
- [x] Deployment tasks (for both demo and production — start with demo to document/confirm process, then do for prod)
 - [x] Create S3 buckets (make them private)
   - [x] demo
    - [x] prod
 - [x] Create siloed AWS AMI accounts with only access to the specified buckets
   - [x] demo
    - [x] prod
 - [x] Add env vars for AWS secret key ID and AWS secret access key
   - [x] demo
    - [x] prod
 - [x] Add env vars for EW username and password
   - [x] demo
    - [x] prod
 - [x] Add env vars for S3 bucket name and S3 host name
   - [x] demo
    - [x] prod
 - [x] Run database migrations
   - [x] demo
    - [x] prod
 - [x] Test full flow on demo
 - [x] Push to prod
- [x] Send release notes/FU with all users

**Comment by lippytak** [comment]
Adding note about RM training

**Comment by daguar** [comment]
Progress bar styling done! Thanks @alanjosephwilliams

**Comment by daguar** [comment]
Fixed the URL in email

**Comment by daguar** [comment]
I added to the release list "Printable confirmation page (and/or copy that makes sense with doc upload done) ( #355 )" based on conversation in that issue.

**Comment by daguar** [comment]
Friendly error messages done, w0000t! :fist: @alanjosephwilliams

**Comment by alanjosephwilliams** [comment]
styles for #494 pushed, moving onto confirmation page

**Comment by daguar** [comment]
:+1: merged!

**Comment by lippytak** [comment]
Pinged RM with sample email. Will check in tomorrow.

BTW @daguar can we make their username **sfhsa**?

**Comment by daguar** [comment]
@lippytak :+1: to making username sfhsa (though now it's public :P )

**Comment by lippytak** [comment]
Just successfully tested 10, 20, and 40 'take a photo' uploads on mobile. Looks good :+1: !
![screen shot 2015-04-27 at 8 30 07 am](https://cloud.githubusercontent.com/assets/2533112/7351084/e5fdb018-ecb7-11e4-88dd-ab5da62455b0.png)

One upload got stuck on 20 docs but eventually errored out with the 'bad file type' error message (wrong). I'll re-open the other issue and give @daguar a timestamp to look into it.

**Comment by lippytak** [comment]
Removing the BG release requirement from OG comment above: ' PDFs with lots of pages = request timeout at end (but backend is okay) — may require background job implementation ( #496 )'

**Comment by alanjosephwilliams** [comment]
Woo wooooo

On Mon, Apr 27, 2015 at 8:35 AM, Jake Solomon <notifications@github.com>
wrote:

> Removing the BG release requirement from OG comment above: ' PDFs with
> lots of pages = request timeout at end (but backend is okay) — may require
> background job implementation ( #496
> <https://github.com/codeforamerica/clean/issues/496> )'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/504#issuecomment-96712635>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Removed "printable confirmation page" issue reference and replaced with "Change final page (new page/route) to have text that reflects that the user has already uploaded documents" per our collective understanding

**Comment by daguar** [comment]
Updated to add
- [x] Show different error for bad filetype vs. general error (which we'll say to retry on)
which is done! :shipit:

**Comment by daguar** [comment]
Checked off final page confirmation. Thanks @alanjosephwilliams!

**Comment by daguar** [comment]
Added deployment tasks

**Comment by daguar** [comment]
Started on deployment tasks

**Comment by daguar** [comment]
Credentials are stored in the private creds doc

**Comment by daguar** [comment]
Successfully tested on demo

**Comment by daguar** [comment]
Live on dev, demo, and production. :shipit: :+1: 

@lippytak — Last task is release notes to users, and then this is good to close!

**Comment by lippytak** [comment]
Release email sent to all users.

@daguar do a final gut check but I think we're :+1: to close this.

**Comment by daguar** [comment]
:shipit:

**Comment by daguar** [comment]
Some stats so far:

- 7 cases submitted since release
- 4 cases had documents attached
- Distribution of # of docs per case = 2, 4, 10, 14
